baseURL: "/"
title: jonathanmarcantonio
paginate: 5
theme: 
  - MyChanges
  - PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Jonathan Marcantonio's Portfolio Website"
    keywords: [Blog, Portfolio, PaperMod]
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        favicon: "images/favicon.png"



    # profile-mode
    profileMode:
        enabled: true
        title: "Jonathan Marcantonio"
        

        imageUrl: "images/picofme.jpg" # optional
        imageTitle: "Just a picture of myself" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/lennysgarage"
        - name: "Email"
          url: "mailto:jonathan.marcantonio@mail.utoronto.ca"
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/jonathan-marcantonio"
        - name: "Letterboxd"
          url: "https://letterboxd.com/lennysgarage/"


    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page


    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: About
          url: /about/
          weight: 10
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 20
        - identifier: resume
          name: Resume
          url: /documents/JMResume.pdf
          weight: 30
        - identifer: search
          name: Search
          url: /search/
          weight: 40

# Allows for my inline js in markdown
markup:
  goldmark:
    renderer:
      unsafe: true
